### ISSUE TITLE
Empty creative mode tab

### ISSUE THREAD

**Issue by 9Octopus** [BiggerSeries/Quartz#11]
Is this intentional?

![image](https://user-images.githubusercontent.com/69008304/226688138-1a18c45a-0ed9-4799-911d-c08ca5c645b0.png)

**Comment by RogueLogix** [comment]
Intentional, no.
Expected, yes.

This is a side effect of my common registry code for Phos, Quartz, and BiggerReactors, which automatically creates a creative tab for all registered items, of which Quartz registers none, so its empty. Quartz specific demo/debug blocks may also be added eventually, so its not something I'm going to fix.
