### ISSUE TITLE
1.20.1 cannot build ( Windows 10 )

### ISSUE THREAD

**Issue by XDuskAshes** [BiggerSeries/Quartz#24]
Greetings.

I am attempting to build Quartz ( as well as Phosphophyllite ) for 1.20.1 using the 1.20.1 branch here, with the respective Phosphophyllite submodule cloned as well. I receive this upon running ``.\gradlew.bat`` from CMD or Powershell:

```
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/8.1.1/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build

FAILURE: Build failed with an exception.

* What went wrong:
Could not open cp_settings generic class cache for settings file 'C:\Users\(MY USERNAME)\Desktop\code\gclone\quartz\settings.gradle' (C:\Users\(MY USERNAME)\.gradle\caches\8.1.1\scripts\8farkbqq161ny89siihe5e4tz).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
```

I've never handmade any Minecraft mods, ergo I'm not familiar with the half of this. I would just like some assistance so I can get this build working so I can tinker.

**Comment by RogueLogix** [comment]
Seems that error is because of the wrong Java version being used. 1.18 and newer used Java 17, so make sure you are using that version. Also, the 1.20.1 branch is in a weird state, and probably not what you would want to tinker with. 1.20.1-LF is the Legacy Forge version that is the current latest shipped version.

If that's not the issue, and you still need further help, discord (linked on curseforge) is a better place to ask me for help with this than GitHub is, so I'm going to close the issue.
